#!/bin/bash

file_name=$1


while IFS="\n" read -r line
do
  key=$(echo "$line" | cut -d '=' -f 1)
  value=$(echo "$line" | cut -d '=' -f 2)

  #Remove Front spaces for key
  key=$(echo "$key" | sed 's/^[[:space:]]*//')
  #Remove Back spaces for key
  key=$(echo "$key" | sed 's/[[:space:]]*$//')

  #Remove Front spaces for value
  value=$(echo "$value" | sed 's/^[[:space:]]*//')
  #Remove Back spaces for value
  value=$(echo "$value" | sed 's/[[:space:]]*$//')

  value=$(echo "$value" | sed 's/[\/&]/\\&/g')

  #Apply these condition on two spaces
  sed -i "s/<< $key >>/$value/g"

  #Apply these condition on no spaces
  sed -i "s/<<$key>>/$value/g"

done < $file_name
