apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      labels:
        type: demo
    spec:
      containers:
        - name: ajay
          image: docker.io/ajaya001/argocd-private
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: vault-example
