
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 2
  template:
    metadata:
      name: demo-pod
    spec:
      containers:
        - name: c1
          image: ajaya001/my-doc-repo:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
       - name: repo-secret 
---
