
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      name: demo-pod
      labels:
        type: demo
    spec:
      containers:
        - name: c1
          image: ajaya001/argocd-private
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        imagePullSecrets:
       - name: dev-registry-access
---
