kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: 167016c5-bdee-e7ae-896a-46d9518bcb0c
  AVP_SECRET_ID: 9877143f-7874-c9c5-8fd1-505f15ce050d
  AVP_TYPE: vault
  VAULT_ADDR: http://127.0.0.1:8200