resources:
  - ../../base
namePrefix: dev-
nameSuffix: devsuffix
namespace: dev
replicas:
  - name: my-application
    count: 3
patchesJson6902:
  - target:
      kind: Deployment
      name: my-application
    path: patch.yaml
  - |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-application
      spec:
        template:
          spec:
            containers:
              - name: containerfromdev
        
