resources:
- ../../base
namePrefix: dev-
nameSuffix: devsuffix
namespace: dev
replicas:
- name: my-application
  count: 5
patchesJson6902:
- target:
    kind: Deployment
    name: my-application
  patch: |-
    - op: replace
      path: /spec/replicas
      value: dev-replica-count
- target:
    kind: Deployment
    name: my-application
  path: patch.yaml
