resources:
- ../../base
patchesJson6902:
- target:
    kind: Deployment
    name: my-application
  patch: |-
    - op: replace
      path: /spec/replicas
      value: replica-count
- target:
    kind: Deployment
    name: my-application
  path: patch.yaml
