resources:
- ../../base
patchesJson6902:
- target:
    kind: Deployment
    name: my-application
  patch: |-
    - op: replace
      path: /metadata/name
      value: container-name
    - op: replace
      path: /spec/replicas
      value: replica-count
