resources:
- ../../base
namePrefix: prod-
nameSuffix: prodsuffix
namespace: prod
replicas:
- name: my-application
  count: 4
patchesJson6902:
- target:
    kind: Deployment
    name: my-application
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: CONTAINER_NAME
images:
- name: docker.io/ajaya001/argocd-private
  newTag: v3000
