resources:
- ../../base
namePrefix: qa-
nameSuffix: qaend
namespace: qa
replicas:
- name: my-application
  count: 5
patchesJson6902:
- target:
    kind: Deployment
    name: my-application
  path: patch.yaml
- target:
    kind: Deployment
    name: my-application
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: containersfromqa
replacements:
- source:
    kind: Deployment
    name: my-application
    fieldPath: spec.template.spec.containers.0.ports.0.containerPort
  targets:
  - select:
      kind: Service
      name: my-application-service
    fieldPaths:
    - spec.ports.0.targetPort
images:
- name: docker.io/ajaya001/argocd-private
  newTag: v24
