resources:
  - ../../base
namePrefix: qa-
nameSuffix: qaend
namespace: qa
replicas:
  - name: my-application
    count: 5
patchesJson6902:
  - target:
      kind: Deployment
      name: my-application
    path: patch.yaml
  - target:
      kind: Deployment
      name: my-application
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: containersfrompatch