resources:
  - ../../base
namePrefix: qa-
nameSuffix: qaend
namespace: qa
replicas:
  - name: my-application
    count: 5
patchesJson6902:
  - target:
      kind: Deployment
      name: my-application
    path: patch.yaml